# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 459e15ad8a9f974aa78d939179abf2b3fe312b25363230482b791bf73803c49d9a1db24a2a61dde5b6db82b0811a422b250401c02b0a24376c0973df9b33941a

test:
  secret_key_base: 458dfb1d447b7e3ede6800cbb1ac3b3365298251bccae0fa278d47f5fb8dcda20479bbb3c0be22ba82325fb08d2c15e3b6c1c9a29e3d0d63c74823cfc51d80bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
